name: linter

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: python3 -m pip install black
      - run: python3 -m black --check --verbose --diff deepip

  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: python3 -m pip install pylint
      - run: python3 -m pylint deepip
