name: tests

on:
  pull_request:
  push:
  workflow_run:
    workflows: ["linter"]
    types: [completed]


jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: python3 -m pip install pytest
      - run: python3 -m pytest tests
