name: tests

on: [pull_request]

jobs:
  pytest:
    needs: linter
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: python3 -m pip install pytest
      - run: python3 -m pytest tests
